var searchData=
[
  ['timeout_20tt_20property_20tt_0',['Timeout &lt;tt&gt;property&lt;/tt&gt;',['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md45',1,'']]],
  ['tt_20constants_20tt_1',['GameVideoDownload &lt;tt&gt;constants&lt;/tt&gt;',['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md26',1,'']]],
  ['tt_20constructor_20tt_2',['#ctor(credentials,apiServerParameters,userThreads) &lt;tt&gt;constructor&lt;/tt&gt;',['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md30',1,'']]],
  ['tt_20method_20tt_3',['GetStrings(objectUris,objectName,cancellationToken,progress) &lt;tt&gt;method&lt;/tt&gt;',['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md20',1,'']]],
  ['tt_20property_20tt_4',['tt property tt',['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md4',1,'CRC &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md35',1,'DataObject &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md6',1,'MD5 &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md8',1,'MediaFormat &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md10',1,'MediaTypeName &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md12',1,'ObjectID &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md37',1,'ProgressPercentage &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md39',1,'Rate &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md14',1,'SHA1 &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md16',1,'SystemID &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md45',1,'Timeout &lt;tt&gt;property&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md41',1,'Uri &lt;tt&gt;property&lt;/tt&gt;']]],
  ['tt_20type_20tt_5',['tt type tt',['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md18',1,'ApiDataService &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md2',1,'APIDownloadParameters &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md24',1,'ApiQueryType &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md28',1,'GetData &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md33',1,'ProgressChangedEventArgs &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md43',1,'WebClient &lt;tt&gt;type&lt;/tt&gt;']]],
  ['type_20tt_6',['type tt',['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md18',1,'ApiDataService &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md2',1,'APIDownloadParameters &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md24',1,'ApiQueryType &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md28',1,'GetData &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md33',1,'ProgressChangedEventArgs &lt;tt&gt;type&lt;/tt&gt;'],['../md_stigzler_8_screenscraper_2bin_2_debug_2_documentation_2.html#autotoc_md43',1,'WebClient &lt;tt&gt;type&lt;/tt&gt;']]]
];
